#!/usr/bin/env bash
# Debug helper: dump every UserPromptSubmit hook payload to a file.
#
# Usage:
#   1. Run this from the repo root:    ./tools/debug_hook_payload.sh enable
#   2. Trigger a prompt in Claude Code (try pasting something).
#   3. Inspect the dump:                cat /tmp/bp-hook-payload.jsonl
#   4. Restore your normal hook:        ./tools/debug_hook_payload.sh disable
#
# Replaces (temporarily) the Better Phrase hook with this logger, so it sees
# exactly what Claude Code sends. Output appends to /tmp/bp-hook-payload.jsonl
# as one JSON object per invocation.

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$( dirname "$SCRIPT_DIR" )"
LOGGER_SHIM="$REPO_DIR/tools/_bp_debug_logger.sh"
NORMAL_HOOK="$REPO_DIR/better-phrase.sh"
SETTINGS="$HOME/.claude/settings.json"
DUMP_FILE="/tmp/bp-hook-payload.jsonl"

mode="${1:-status}"

write_logger() {
  cat > "$LOGGER_SHIM" <<EOF
#!/usr/bin/env bash
# Auto-generated by debug_hook_payload.sh — logs hook payload to ${DUMP_FILE}
set -eu
DUMP="${DUMP_FILE}"
# Read stdin, save a copy, then exit 0 silently (no polish).
input="\$(cat)"
{
  echo "--- \$(date '+%Y-%m-%d %H:%M:%S') ---"
  echo "\$input"
  echo ""
} >> "\$DUMP"
exit 0
EOF
  chmod +x "$LOGGER_SHIM"
}

retarget_hook() {
  local target="$1"
  jq --arg cmd "$target" '
    .hooks.UserPromptSubmit |= [
      .[] |
      if .matcher != null then
        .hooks |= map(if (.command | test("/better-phrase\\.sh$|/_bp_debug_logger\\.sh$")) then .command = $cmd else . end)
      else
        if (.command | test("/better-phrase\\.sh$|/_bp_debug_logger\\.sh$")) then .command = $cmd else . end
      end
    ]
  ' "$SETTINGS" > "$SETTINGS.tmp" && mv "$SETTINGS.tmp" "$SETTINGS"
}

case "$mode" in
  enable)
    write_logger
    retarget_hook "$LOGGER_SHIM"
    echo "✓ Debug logger active."
    echo "  Trigger prompts in Claude Code, then:"
    echo "    cat $DUMP_FILE"
    echo "  To restore the normal hook:"
    echo "    $0 disable"
    ;;
  disable)
    retarget_hook "$NORMAL_HOOK"
    rm -f "$LOGGER_SHIM"
    echo "✓ Normal Better Phrase hook restored."
    if [ -f "$DUMP_FILE" ]; then
      echo "  Dump preserved at: $DUMP_FILE"
      echo "  Remove it with:    rm $DUMP_FILE"
    fi
    ;;
  status|*)
    current=$(jq -r '.hooks.UserPromptSubmit[0].hooks[0].command // .hooks.UserPromptSubmit[0].command' "$SETTINGS" 2>/dev/null || echo "<none>")
    echo "Current UserPromptSubmit command: $current"
    if [ -f "$DUMP_FILE" ]; then
      echo "Dump file exists: $DUMP_FILE ($(wc -l < "$DUMP_FILE") lines)"
    fi
    echo
    echo "Commands:"
    echo "  $0 enable    # swap to debug logger"
    echo "  $0 disable   # restore normal hook"
    echo "  $0 status    # this view"
    ;;
esac
